// <auto-generated />
using System;
using CEN4090L_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CollegeCompanion.Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Needs")
                        .HasColumnType("numeric")
                        .HasColumnName("Needs");

                    b.Property<decimal?>("Savings")
                        .HasColumnType("numeric")
                        .HasColumnName("Savings");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<decimal?>("Wants")
                        .HasColumnType("numeric")
                        .HasColumnName("Wants");

                    b.HasKey("Id");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("CEN4090L_Project.Models.SavingsGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal")
                        .HasColumnName("CurrentAmount");

                    b.Property<decimal>("MonthlyAllocation")
                        .HasColumnType("decimal")
                        .HasColumnName("MonthlyAllocation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("OwnerUserId");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal")
                        .HasColumnName("TargetAmount");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("TargetDate");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavingsGoal");
                });

            modelBuilder.Entity("CEN4090L_Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<float?>("Income")
                        .HasColumnType("real")
                        .HasColumnName("Income");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal")
                        .HasColumnName("Amount");

                    b.Property<int?>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<int?>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("Category");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("DateTime");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("CEN4090L_Project.Models.SavingsGoal", b =>
                {
                    b.HasOne("CEN4090L_Project.Models.User", null)
                        .WithMany("SavingsGoals")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CEN4090L_Project.Models.User", b =>
                {
                    b.HasOne("Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Expense", b =>
                {
                    b.HasOne("Budget", null)
                        .WithMany("Expenses")
                        .HasForeignKey("BudgetId");
                });

            modelBuilder.Entity("Budget", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CEN4090L_Project.Models.User", b =>
                {
                    b.Navigation("SavingsGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
